name: Firmware Build
on:
  workflow_dispatch:

jobs:
  build-left:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build left
        uses: badjeff/zmk-build-action@latest
        with:
          board: nice_nano_v2
          shield: sofle_left
          artifact-name: left
  build-right:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build right
        uses: badjeff/zmk-build-action@latest
        with:
          board: nice_nano_v2
          shield: sofle_right
          artifact-name: right
